# Generated by Django 5.2 on 2025-04-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verify',
            field=models.BooleanField(default=False),
        ),
    ]
