# Generated by Django 5.2 on 2025-04-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_email_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField()),
            ],
        ),
    ]
