# Generated by Django 5.2 on 2025-04-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_trend',
            field=models.BooleanField(default=False),
        ),
    ]
