# Generated by Django 5.2 on 2025-04-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_brand_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_price', models.SmallIntegerField()),
                ('b_price', models.SmallIntegerField()),
            ],
        ),
    ]
