# Generated by Django 5.2 on 2025-04-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_up',
            field=models.BooleanField(default=False),
        ),
    ]
