# Generated by Django 5.2 on 2025-04-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('start_valid', models.DateTimeField()),
                ('expire_valid', models.DateTimeField()),
            ],
        ),
    ]
