# Generated by Django 5.2 on 2025-04-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_price',
            field=models.FloatField(default=0),
        ),
    ]
